"""Generate the corrected literature_matrix.csv with all verified data."""
import csv
from pathlib import Path

docs_dir = Path("docs/novelty")
docs_dir.mkdir(parents=True, exist_ok=True)

fieldnames = [
    "paper_id", "title", "authors", "year", "venue", "peer_reviewed",
    "paper_url", "code_url", "doi", "research_area", "selection_level",
    "task_domain", "number_of_tasks_or_datasets", "number_of_models_or_algorithms",
    "candidate_system_types", "task_or_instance_features", "predicted_outcomes",
    "selection_objective", "evaluation_scheme", "baselines", "uses_oracle",
    "uses_regret", "handles_cost", "handles_latency", "handles_output_validity",
    "main_finding", "main_limitation", "overlap_with_proposed_study",
    "difference_from_proposed_study", "novelty_threat_level", "verification_status",
    "notes", "verification_source", "verification_date", "full_text_checked",
    "correction_notes", "exclusion_reason",
]

papers = [
    # P01 - Rice 1976
    {
        "paper_id": "P01",
        "title": "The Algorithm Selection Problem",
        "authors": "John R. Rice",
        "year": "1976",
        "venue": "Advances in Computers",
        "peer_reviewed": "yes",
        "paper_url": "https://doi.org/10.1016/S0065-2458(08)60520-3",
        "code_url": "not reported",
        "doi": "10.1016/S0065-2458(08)60520-3",
        "research_area": "Algorithm selection",
        "selection_level": "Task",
        "task_domain": "General (numerical)",
        "number_of_tasks_or_datasets": "not reported",
        "number_of_models_or_algorithms": "not reported",
        "candidate_system_types": "numerical algorithms",
        "task_or_instance_features": "problem characteristics",
        "predicted_outcomes": "performance",
        "selection_objective": "best algorithm for given problem",
        "evaluation_scheme": "theoretical framework",
        "baselines": "none",
        "uses_oracle": "yes (defined conceptually)",
        "uses_regret": "no",
        "handles_cost": "yes (abstract cost)",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "Formalizes the algorithm selection problem as mapping from problem space to algorithm space",
        "main_limitation": "Theoretical framework; no empirical evaluation",
        "overlap_with_proposed_study": "Foundational formulation of task-level algorithm selection",
        "difference_from_proposed_study": "No ML models; no text domain; no output validity",
        "novelty_threat_level": "low",
        "verification_status": "partially_verified",
        "notes": "Foundational paper; behind paywall for full text",
        "verification_source": "DOI resolution + secondary citations in Smith-Miles 2009",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "",
        "exclusion_reason": "",
    },
    # P02 - Auto-WEKA
    {
        "paper_id": "P02",
        "title": "Auto-WEKA: Combined Selection and Hyperparameter Optimization of Classification Algorithms",
        "authors": "Chris Thornton, Frank Hutter, Holger H. Hoos, Kevin Leyton-Brown",
        "year": "2013",
        "venue": "KDD",
        "peer_reviewed": "yes",
        "paper_url": "https://dl.acm.org/doi/10.1145/2487575.2487629",
        "code_url": "not reported",
        "doi": "10.1145/2487575.2487629",
        "research_area": "AutoML",
        "selection_level": "Task",
        "task_domain": "Tabular",
        "number_of_tasks_or_datasets": "21",
        "number_of_models_or_algorithms": "39",
        "candidate_system_types": "classical classifiers",
        "task_or_instance_features": "dataset meta-features (for warmstarting)",
        "predicted_outcomes": "accuracy",
        "selection_objective": "maximize classification accuracy",
        "evaluation_scheme": "cross-validation",
        "baselines": "grid search, default WEKA",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "Simultaneous algorithm selection and hyperparameter optimization outperforms manual selection",
        "main_limitation": "Tabular data only; no LLMs or text-specific features",
        "overlap_with_proposed_study": "Task-level portfolio selection from diverse classifiers",
        "difference_from_proposed_study": "No heterogeneous bounded systems; no LLMs; no validity or latency",
        "novelty_threat_level": "low",
        "verification_status": "metadata_verified",
        "notes": "",
        "verification_source": "ACM DL page",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "",
        "exclusion_reason": "",
    },
    # P03 - auto-sklearn
    {
        "paper_id": "P03",
        "title": "Efficient and Robust Automated Machine Learning",
        "authors": "Matthias Feurer, Aaron Klein, Katharina Eggensperger, Jost Tobias Springenberg, Manuel Blum, Frank Hutter",
        "year": "2015",
        "venue": "NeurIPS",
        "peer_reviewed": "yes",
        "paper_url": "https://papers.nips.cc/paper/5872-efficient-and-robust-automated-machine-learning",
        "code_url": "https://github.com/automl/auto-sklearn",
        "doi": "not reported",
        "research_area": "AutoML",
        "selection_level": "Task",
        "task_domain": "Tabular",
        "number_of_tasks_or_datasets": "140",
        "number_of_models_or_algorithms": "15",
        "candidate_system_types": "classical classifiers (scikit-learn)",
        "task_or_instance_features": "meta-features (simple, landmarking, PCA-based)",
        "predicted_outcomes": "accuracy",
        "selection_objective": "maximize accuracy via warmstarted Bayesian optimization",
        "evaluation_scheme": "cross-validation on OpenML benchmarks",
        "baselines": "Auto-WEKA, random search",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "Meta-learning warmstarting significantly improves Bayesian optimization for AutoML",
        "main_limitation": "Homogeneous classical classifiers; tabular data only",
        "overlap_with_proposed_study": "Task-level meta-learning for model selection",
        "difference_from_proposed_study": "No text domain; no LLMs; no output validity; no latency prediction",
        "novelty_threat_level": "low",
        "verification_status": "metadata_verified",
        "notes": "",
        "verification_source": "NeurIPS proceedings page",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "",
        "exclusion_reason": "",
    },
    # P04 - PsyMatrix (CRITICAL NEW ADDITION)
    {
        "paper_id": "P04",
        "title": "Characterizing Text Datasets with Psycholinguistic Features",
        "authors": "Marcio Monteiro, Charu Karakkaparambil James, Marius Kloft, Sophie Fellenz",
        "year": "2024",
        "venue": "Findings of EMNLP 2024",
        "peer_reviewed": "yes",
        "paper_url": "https://aclanthology.org/2024.findings-emnlp.880/",
        "code_url": "not reported",
        "doi": "10.18653/v1/2024.findings-emnlp.880",
        "research_area": "Text-dataset model recommendation",
        "selection_level": "Task",
        "task_domain": "Text classification",
        "number_of_tasks_or_datasets": "146 (derived from 11 base datasets)",
        "number_of_models_or_algorithms": "24",
        "candidate_system_types": "pretrained language models (fine-tuned)",
        "task_or_instance_features": "psycholinguistic features, topic distributions, complexity measures",
        "predicted_outcomes": "model performance (for recommendation)",
        "selection_objective": "recommend optimal or near-optimal pretrained model for fine-tuning",
        "evaluation_scheme": "meta-learning on held-out datasets",
        "baselines": "not verified",
        "uses_oracle": "not verified",
        "uses_regret": "not verified",
        "handles_cost": "no",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "Psycholinguistic dataset embeddings enable effective pretrained model recommendation for text classification",
        "main_limitation": "146 datasets derived from only 11 base datasets; effective independence unclear; only fine-tuned PLMs, no classical models or zero-shot LLMs",
        "overlap_with_proposed_study": "Task-level text-dataset characterization for model recommendation; closest NLP-specific prior work",
        "difference_from_proposed_study": "Only PLMs (fine-tuned); no classical classifiers or generative LLMs; no output validity; no latency; no selection regret; dataset independence concern",
        "novelty_threat_level": "critical",
        "verification_status": "fully_verified",
        "notes": "Pages 14977-14990. Dataset independence is a key concern: 146 derived datasets from 11 bases.",
        "verification_source": "ACL Anthology page: https://aclanthology.org/2024.findings-emnlp.880/",
        "verification_date": "2026-10-03",
        "full_text_checked": "yes (abstract + metadata from ACL Anthology)",
        "correction_notes": "New addition in Task 1B",
        "exclusion_reason": "",
    },
    # P05 - ModelLens (CORRECTED)
    {
        "paper_id": "P05",
        "title": "ModelLens: Finding the Best for Your Task from Myriads of Models",
        "authors": "Rui Cai, Weijie Jacky Mo, Xiaofei Wen, Qiyao Ma, Wenhui Zhu, Xiwen Chen, Muhao Chen, Zhe Zhao",
        "year": "2026",
        "venue": "arXiv",
        "peer_reviewed": "no",
        "paper_url": "https://arxiv.org/abs/2605.07075",
        "code_url": "not reported",
        "doi": "10.48550/arXiv.2605.07075",
        "research_area": "Performance prediction / Model recommendation",
        "selection_level": "Task",
        "task_domain": "Text, Vision-Language",
        "number_of_tasks_or_datasets": "9600",
        "number_of_models_or_algorithms": "47000",
        "candidate_system_types": "pretrained models (open-source ecosystem)",
        "task_or_instance_features": "performance-aware latent space over model-dataset-metric tuples",
        "predicted_outcomes": "model performance ranking on unseen datasets",
        "selection_objective": "recommend best models without running them on target dataset",
        "evaluation_scheme": "held-out tasks; 1.62M evaluation records",
        "baselines": "metadata-only baselines, per-model forward-pass methods",
        "uses_oracle": "not verified",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "Latent space from leaderboard interactions can rank unseen models on unseen datasets; improves routing methods by up to 81%",
        "main_limitation": "Requires public leaderboard data; no cost/latency/validity modeling",
        "overlap_with_proposed_study": "Task-level performance prediction on unseen tasks without running candidates",
        "difference_from_proposed_study": "No operational behavior prediction; no classical classifiers; no output validity; no selection regret as outcome",
        "novelty_threat_level": "high",
        "verification_status": "fully_verified",
        "notes": "",
        "verification_source": "arXiv page: https://arxiv.org/abs/2605.07075",
        "verification_date": "2026-10-03",
        "full_text_checked": "yes (abstract verified from arXiv)",
        "correction_notes": "Corrected from P08: was Jiang et al. 2024 arXiv:2405.00000 (fabricated). Now Cai et al. 2026 arXiv:2605.07075.",
        "exclusion_reason": "",
    },
    # P06 - LLMRouterBench (CORRECTED)
    {
        "paper_id": "P06",
        "title": "LLMRouterBench: A Massive Benchmark and Unified Framework for LLM Routing",
        "authors": "Hao Li, Yiqun Zhang, Zhaoyan Guo, Chenxu Wang, Shengji Tang, Qiaosheng Zhang, Yang Chen, Biqing Qi, Peng Ye, Lei Bai, Zhen Wang, Shuyue Hu",
        "year": "2026",
        "venue": "arXiv",
        "peer_reviewed": "no",
        "paper_url": "https://arxiv.org/abs/2601.07206",
        "code_url": "https://github.com/ynulihao/LLMRouterBench",
        "doi": "10.48550/arXiv.2601.07206",
        "research_area": "LLM routing",
        "selection_level": "Query",
        "task_domain": "Text (multiple NLP tasks)",
        "number_of_tasks_or_datasets": "21",
        "number_of_models_or_algorithms": "33",
        "candidate_system_types": "LLMs",
        "task_or_instance_features": "prompt embeddings",
        "predicted_outcomes": "accuracy; enables latency-aware analysis",
        "selection_objective": "performance-oriented and performance-cost trade-off routing",
        "evaluation_scheme": "unified evaluation of 10 routing baselines on held-out queries",
        "baselines": "10 representative routing baselines including commercial routers",
        "uses_oracle": "yes",
        "uses_regret": "yes (gap to oracle reported)",
        "handles_cost": "yes",
        "handles_latency": "yes (enables latency-aware analysis)",
        "handles_output_validity": "no",
        "main_finding": "Many routing methods perform similarly under unified evaluation; commercial routers fail to reliably outperform simple baselines; substantial gap remains to oracle",
        "main_limitation": "Query-level; homogeneous LLM portfolio only; no classical or encoder models",
        "overlap_with_proposed_study": "Cost/latency objectives; oracle/regret evaluation; multiple routing baselines",
        "difference_from_proposed_study": "Query-level not task-level; homogeneous LLM-only portfolio; no output validity modeling",
        "novelty_threat_level": "high",
        "verification_status": "fully_verified",
        "notes": "No peer-reviewed version found as of search date. Title is 'Massive' not 'Large-scale'.",
        "verification_source": "arXiv page: https://arxiv.org/abs/2601.07206",
        "verification_date": "2026-10-03",
        "full_text_checked": "yes (abstract from arXiv)",
        "correction_notes": "Corrected from P04: authors were Wu et al. (wrong). Now Li et al.",
        "exclusion_reason": "",
    },
    # P07 - RouterBench (CORRECTED)
    {
        "paper_id": "P07",
        "title": "RouterBench: A Benchmark for Multi-LLM Routing System",
        "authors": "Qitian Jason Hu, Jacob Bieker, Xiuyu Li, Nan Jiang, Benjamin Keigwin, Gaurav Ranganath, Kurt Keutzer, Shriyash Kaustubh Upadhyay",
        "year": "2024",
        "venue": "arXiv",
        "peer_reviewed": "no",
        "paper_url": "https://arxiv.org/abs/2403.12031",
        "code_url": "https://github.com/withmartian/routerbench",
        "doi": "10.48550/arXiv.2403.12031",
        "research_area": "LLM routing",
        "selection_level": "Query",
        "task_domain": "Text",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "LLMs",
        "task_or_instance_features": "query characteristics",
        "predicted_outcomes": "accuracy, cost",
        "selection_objective": "cost-effective routing",
        "evaluation_scheme": "405k+ inference outcomes; theoretical framework for router assessment",
        "baselines": "various routing approaches compared",
        "uses_oracle": "yes (theoretical framework)",
        "uses_regret": "yes",
        "handles_cost": "yes",
        "handles_latency": "not verified",
        "handles_output_validity": "no",
        "main_finding": "Provides theoretical framework and standardized benchmark for LLM routing evaluation",
        "main_limitation": "Query-level; LLM-only portfolio",
        "overlap_with_proposed_study": "Routing benchmark design; regret evaluation",
        "difference_from_proposed_study": "Query-level; no classical models; no output validity",
        "novelty_threat_level": "high",
        "verification_status": "fully_verified",
        "notes": "Previously incorrectly attributed to Ding et al. Ding et al. wrote Hybrid LLM (separate paper).",
        "verification_source": "arXiv page: https://arxiv.org/abs/2403.12031",
        "verification_date": "2026-10-03",
        "full_text_checked": "yes (abstract from arXiv)",
        "correction_notes": "Corrected from P05: was attributed to Ding et al. Now Hu et al.",
        "exclusion_reason": "",
    },
    # P08 - RouteJudge (CORRECTED)
    {
        "paper_id": "P08",
        "title": "RouteJudge: An Open Platform for Reproducible and Preference-Aware LLM Routing",
        "authors": "Guannan Lai, Haoran Hu, Han-Jia Ye",
        "year": "2026",
        "venue": "arXiv",
        "peer_reviewed": "no",
        "paper_url": "https://arxiv.org/abs/2606.18774",
        "code_url": "https://github.com/LAMDA-Model-Reuse/ORBIT",
        "doi": "10.48550/arXiv.2606.18774",
        "research_area": "LLM routing",
        "selection_level": "Query",
        "task_domain": "Text",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "LLMs",
        "task_or_instance_features": "query, routing decisions, task metadata",
        "predicted_outcomes": "preference, cost, latency",
        "selection_objective": "preference-aware, cost-aware, task-conditioned router evaluation",
        "evaluation_scheme": "online pairwise preference evaluation",
        "baselines": "offline evaluation methods",
        "uses_oracle": "not verified",
        "uses_regret": "not verified",
        "handles_cost": "yes",
        "handles_latency": "yes",
        "handles_output_validity": "no",
        "main_finding": "Online pairwise preference evaluation better captures router-level decision quality than offline methods",
        "main_limitation": "Focuses on LLM-to-LLM routing preference; no heterogeneous models",
        "overlap_with_proposed_study": "Cost and latency tracking; task metadata in evaluation",
        "difference_from_proposed_study": "Query-level; online preference focus; no classical models; no output validity",
        "novelty_threat_level": "moderate",
        "verification_status": "fully_verified",
        "notes": "Also releases ORBIT toolbox. No peer-reviewed acceptance found.",
        "verification_source": "arXiv page: https://arxiv.org/abs/2606.18774",
        "verification_date": "2026-10-03",
        "full_text_checked": "yes (abstract from arXiv)",
        "correction_notes": "Corrected from P06: was Katz et al., arXiv:2606.07174, wrong title. Now Lai et al., arXiv:2606.18774.",
        "exclusion_reason": "",
    },
    # P09 - RouterArena (CORRECTED)
    {
        "paper_id": "P09",
        "title": "RouterArena: An Open Platform for Comprehensive Comparison of LLM Routers",
        "authors": "Yifan Lu, Rixin Liu, Jiayi Yuan, Xingqi Cui, Shenrun Zhang, Hongyi Liu, Jiarong Xing",
        "year": "2025",
        "venue": "arXiv",
        "peer_reviewed": "no",
        "paper_url": "https://arxiv.org/abs/2510.00202",
        "code_url": "https://github.com/RouteWorks/RouterArena",
        "doi": "10.48550/arXiv.2510.00202",
        "research_area": "LLM routing",
        "selection_level": "Query",
        "task_domain": "Text",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "LLMs",
        "task_or_instance_features": "query text, domain",
        "predicted_outcomes": "accuracy, cost",
        "selection_objective": "comprehensive router comparison",
        "evaluation_scheme": "multi-domain dataset with difficulty levels; automated leaderboard",
        "baselines": "multiple LLM routers compared",
        "uses_oracle": "not verified",
        "uses_regret": "not verified",
        "handles_cost": "yes",
        "handles_latency": "not verified",
        "handles_output_validity": "no",
        "main_finding": "Provides standardized platform for LLM router comparison across domains and difficulty levels",
        "main_limitation": "LLM-only portfolio; no classical models",
        "overlap_with_proposed_study": "Benchmark design for routing evaluation",
        "difference_from_proposed_study": "Query-level; only LLMs; no output validity",
        "novelty_threat_level": "moderate",
        "verification_status": "fully_verified",
        "notes": "Previous matrix had wrong arXiv ID (2511.06647) and wrong authors (Chen et al.).",
        "verification_source": "arXiv page: https://arxiv.org/abs/2510.00202",
        "verification_date": "2026-10-03",
        "full_text_checked": "yes (abstract from arXiv)",
        "correction_notes": "Corrected from P07: was Chen et al. 2025 arXiv:2511.06647. Now Lu et al. 2025 arXiv:2510.00202.",
        "exclusion_reason": "",
    },
    # P10 - Beyond Accuracy and Cost (CORRECTED)
    {
        "paper_id": "P10",
        "title": "Beyond Accuracy and Cost: Latency-Aware LLM Query Routing for Dynamic Workloads",
        "authors": "Shivam Patel, Akaash R. Parthasarathy, Ankur Mallick, Gauri Joshi",
        "year": "2026",
        "venue": "arXiv",
        "peer_reviewed": "no",
        "paper_url": "https://arxiv.org/abs/2607.18253",
        "code_url": "not reported",
        "doi": "10.48550/arXiv.2607.18253",
        "research_area": "LLM routing",
        "selection_level": "Query",
        "task_domain": "Text",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "LLMs",
        "task_or_instance_features": "query prompt length, workload state",
        "predicted_outcomes": "accuracy, latency (TTFT), cost",
        "selection_objective": "joint optimization of latency, accuracy, and cost",
        "evaluation_scheme": "simulated dynamic workloads",
        "baselines": "latency-agnostic routers, standard load-balancing (round-robin, JSQ)",
        "uses_oracle": "not verified",
        "uses_regret": "not verified",
        "handles_cost": "yes",
        "handles_latency": "yes (lightweight latency estimator)",
        "handles_output_validity": "no",
        "main_finding": "Joint latency-accuracy-cost optimization yields up to 40% improvement in accuracy-cost utility",
        "main_limitation": "Query-level; LLM-only; focuses on serving infrastructure latency",
        "overlap_with_proposed_study": "Operational behavior prediction (latency); multi-objective routing",
        "difference_from_proposed_study": "Query-level; LLM-only; infrastructure latency not task-level prediction",
        "novelty_threat_level": "moderate",
        "verification_status": "fully_verified",
        "notes": "",
        "verification_source": "arXiv page: https://arxiv.org/abs/2607.18253",
        "verification_date": "2026-10-03",
        "full_text_checked": "yes (abstract from arXiv)",
        "correction_notes": "Corrected from P12: was Unknown authors, year 2024. Now Patel et al. 2026.",
        "exclusion_reason": "",
    },
    # P11 - FrugalGPT (NEW)
    {
        "paper_id": "P11",
        "title": "FrugalGPT: How to Use Large Language Models While Reducing Cost and Improving Performance",
        "authors": "Lingjiao Chen, Matei Zaharia, James Zou",
        "year": "2023",
        "venue": "arXiv",
        "peer_reviewed": "no",
        "paper_url": "https://arxiv.org/abs/2305.05176",
        "code_url": "not reported",
        "doi": "10.48550/arXiv.2305.05176",
        "research_area": "LLM routing / cascade",
        "selection_level": "Query",
        "task_domain": "Text",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "LLMs (API-based)",
        "task_or_instance_features": "query text",
        "predicted_outcomes": "accuracy, cost",
        "selection_objective": "minimize cost while maintaining accuracy",
        "evaluation_scheme": "empirical comparison on NLP tasks",
        "baselines": "individual LLMs (GPT-4, ChatGPT)",
        "uses_oracle": "not verified",
        "uses_regret": "not verified",
        "handles_cost": "yes",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "LLM cascade can match GPT-4 with up to 98% cost reduction or improve accuracy by 4% at same cost",
        "main_limitation": "Query-level; LLM-only cascade; no classical models",
        "overlap_with_proposed_study": "Cost-aware model selection from heterogeneous API models",
        "difference_from_proposed_study": "Query-level; only LLM APIs; no task-level prediction; no classical models; no output validity",
        "novelty_threat_level": "moderate",
        "verification_status": "fully_verified",
        "notes": "Foundational LLM routing paper",
        "verification_source": "arXiv page: https://arxiv.org/abs/2305.05176",
        "verification_date": "2026-10-03",
        "full_text_checked": "yes (abstract from arXiv)",
        "correction_notes": "New addition in Task 1B",
        "exclusion_reason": "",
    },
    # P12 - RouteLLM (NEW)
    {
        "paper_id": "P12",
        "title": "RouteLLM: Learning to Route LLMs with Preference Data",
        "authors": "Isaac Ong, Amjad Almahairi, Vincent Wu, Wei-Lin Chiang, Tianhao Wu, Joseph E. Gonzalez, M Waleed Kadous, Ion Stoica",
        "year": "2024",
        "venue": "ICLR 2025",
        "peer_reviewed": "yes",
        "paper_url": "https://arxiv.org/abs/2406.18665",
        "code_url": "https://github.com/lm-sys/RouteLLM",
        "doi": "10.48550/arXiv.2406.18665",
        "research_area": "LLM routing",
        "selection_level": "Query",
        "task_domain": "Text",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "2 (strong vs weak)",
        "candidate_system_types": "LLMs",
        "task_or_instance_features": "query text, human preference data",
        "predicted_outcomes": "response quality",
        "selection_objective": "balance cost and quality via binary routing",
        "evaluation_scheme": "standard benchmarks; transfer learning evaluation",
        "baselines": "always-strong, always-weak",
        "uses_oracle": "not verified",
        "uses_regret": "not verified",
        "handles_cost": "yes",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "Router trained on preference data reduces costs >2x without quality loss; transfers across model swaps",
        "main_limitation": "Binary strong/weak routing only; LLM-only",
        "overlap_with_proposed_study": "Cost-aware model routing",
        "difference_from_proposed_study": "Query-level binary routing; no task-level prediction; no classical models; no validity",
        "novelty_threat_level": "moderate",
        "verification_status": "fully_verified",
        "notes": "Published at ICLR 2025 (peer-reviewed)",
        "verification_source": "arXiv page: https://arxiv.org/abs/2406.18665; ICLR 2025 proceedings",
        "verification_date": "2026-10-03",
        "full_text_checked": "yes (abstract from arXiv)",
        "correction_notes": "New addition in Task 1B",
        "exclusion_reason": "",
    },
    # P13 - Hybrid LLM (NEW, separated from RouterBench)
    {
        "paper_id": "P13",
        "title": "Hybrid LLM: Cost-Efficient and Quality-Aware Query Routing",
        "authors": "Dujian Ding, Ankur Mallick, Chi Wang, Robert Sim, Subhabrata Mukherjee, Victor Ruhle, Laks V.S. Lakshmanan, Ahmed Hassan Awadallah",
        "year": "2024",
        "venue": "ICLR 2024",
        "peer_reviewed": "yes",
        "paper_url": "https://arxiv.org/abs/2404.14618",
        "code_url": "not reported",
        "doi": "10.48550/arXiv.2404.14618",
        "research_area": "LLM routing",
        "selection_level": "Query",
        "task_domain": "Text",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "2 (small vs large LLM)",
        "candidate_system_types": "LLMs (small + large)",
        "task_or_instance_features": "predicted query difficulty",
        "predicted_outcomes": "response quality",
        "selection_objective": "dynamically trade quality for cost at test time",
        "evaluation_scheme": "empirical; quality threshold tuning",
        "baselines": "always-large model",
        "uses_oracle": "not verified",
        "uses_regret": "not verified",
        "handles_cost": "yes",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "Up to 40% fewer calls to large model with no quality drop via difficulty-based routing",
        "main_limitation": "Binary routing; LLM-only; no classical models",
        "overlap_with_proposed_study": "Quality-cost trade-off; model routing",
        "difference_from_proposed_study": "Query-level; binary LLM routing; no task-level; no classical models; no validity",
        "novelty_threat_level": "moderate",
        "verification_status": "fully_verified",
        "notes": "Now correctly separated from RouterBench (Hu et al.)",
        "verification_source": "arXiv page: https://arxiv.org/abs/2404.14618; ICLR 2024 proceedings",
        "verification_date": "2026-10-03",
        "full_text_checked": "yes (abstract from arXiv)",
        "correction_notes": "New addition in Task 1B; was previously conflated with RouterBench as 'Ding et al.'",
        "exclusion_reason": "",
    },
    # P14 - Constrained Sequence-to-Tree
    {
        "paper_id": "P14",
        "title": "Constrained Sequence-to-Tree Generation for Hierarchical Text Classification",
        "authors": "Yu et al.",
        "year": "2022",
        "venue": "SIGIR",
        "peer_reviewed": "yes",
        "paper_url": "https://arxiv.org/abs/2204.00811",
        "code_url": "not reported",
        "doi": "not reported",
        "research_area": "Constrained decoding",
        "selection_level": "Instance",
        "task_domain": "Text classification (hierarchical)",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "1",
        "candidate_system_types": "Seq2seq model",
        "task_or_instance_features": "text",
        "predicted_outcomes": "hierarchical labels",
        "selection_objective": "label hierarchy consistency",
        "evaluation_scheme": "accuracy metrics",
        "baselines": "flat classifiers",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "no",
        "handles_output_validity": "yes (enforces hierarchy)",
        "main_finding": "Constrained decoding enforces hierarchical label validity in generation",
        "main_limitation": "Single-model methodology; not a selection problem",
        "overlap_with_proposed_study": "Output contract validity enforcement",
        "difference_from_proposed_study": "Not a task-level selector; single model; no portfolio selection",
        "novelty_threat_level": "low",
        "verification_status": "metadata_verified",
        "notes": "",
        "verification_source": "arXiv page: https://arxiv.org/abs/2204.00811",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "",
        "exclusion_reason": "",
    },
    # P15 - Lazy-k
    {
        "paper_id": "P15",
        "title": "Lazy-k Decoding: Constrained Decoding for Token-Level Sequence Labeling",
        "authors": "Hemmer et al.",
        "year": "2023",
        "venue": "EMNLP",
        "peer_reviewed": "yes",
        "paper_url": "https://arxiv.org/abs/2312.03367",
        "code_url": "not reported",
        "doi": "not reported",
        "research_area": "Constrained decoding",
        "selection_level": "Instance",
        "task_domain": "Token classification",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "1",
        "candidate_system_types": "Language models",
        "task_or_instance_features": "text",
        "predicted_outcomes": "token labels under structural constraints",
        "selection_objective": "maximize probability under structural constraints",
        "evaluation_scheme": "F1 score",
        "baselines": "Viterbi decoding",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "no",
        "handles_output_validity": "yes (structural constraints enforced)",
        "main_finding": "Flexible trade-off between decoding time and structural constraint satisfaction",
        "main_limitation": "Methodology paper; not a system selection problem",
        "overlap_with_proposed_study": "Output validity enforcement methodology",
        "difference_from_proposed_study": "Not related to algorithm selection or routing",
        "novelty_threat_level": "low",
        "verification_status": "metadata_verified",
        "notes": "",
        "verification_source": "arXiv page: https://arxiv.org/abs/2312.03367",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "",
        "exclusion_reason": "",
    },
    # P16 - Constrained Decoding Cross-lingual
    {
        "paper_id": "P16",
        "title": "Constrained Decoding for Cross-lingual Label Projection",
        "authors": "Behzad et al.",
        "year": "2024",
        "venue": "ACL",
        "peer_reviewed": "yes",
        "paper_url": "https://arxiv.org/abs/2402.03131",
        "code_url": "not reported",
        "doi": "not reported",
        "research_area": "Constrained decoding",
        "selection_level": "Instance",
        "task_domain": "Cross-lingual NER",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "1",
        "candidate_system_types": "LLMs",
        "task_or_instance_features": "text",
        "predicted_outcomes": "projected labels",
        "selection_objective": "label projection quality",
        "evaluation_scheme": "F1 score",
        "baselines": "marker-based methods",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "no",
        "handles_output_validity": "yes (prevents label hallucination)",
        "main_finding": "Constrained decoding prevents invalid label generation in cross-lingual transfer",
        "main_limitation": "Not a selection problem",
        "overlap_with_proposed_study": "Output contract validity",
        "difference_from_proposed_study": "Focuses on cross-lingual transfer method, not model selection",
        "novelty_threat_level": "low",
        "verification_status": "metadata_verified",
        "notes": "",
        "verification_source": "arXiv page: https://arxiv.org/abs/2402.03131",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "",
        "exclusion_reason": "",
    },
    # P17 - Lost in Space (grammar-constrained)
    {
        "paper_id": "P17",
        "title": "Lost in Space: Optimizing Tokens for Grammar-Constrained Decoding",
        "authors": "Hamilton, Mimno",
        "year": "2025",
        "venue": "arXiv",
        "peer_reviewed": "no",
        "paper_url": "https://arxiv.org/abs/2502.14969",
        "code_url": "not reported",
        "doi": "10.48550/arXiv.2502.14969",
        "research_area": "Constrained decoding",
        "selection_level": "Instance",
        "task_domain": "Text generation",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "1",
        "candidate_system_types": "LLMs",
        "task_or_instance_features": "grammar specifications",
        "predicted_outcomes": "valid structured sequences",
        "selection_objective": "generation quality under grammar constraints",
        "evaluation_scheme": "validity rate",
        "baselines": "unconstrained generation",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "no",
        "handles_output_validity": "yes (grammar enforcement)",
        "main_finding": "Token optimization improves adherence to grammar constraints",
        "main_limitation": "Methodology paper; not for model selection",
        "overlap_with_proposed_study": "Output validity enforcement methodology",
        "difference_from_proposed_study": "Not related to task-level selection",
        "novelty_threat_level": "low",
        "verification_status": "metadata_verified",
        "notes": "",
        "verification_source": "arXiv page: https://arxiv.org/abs/2502.14969",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "",
        "exclusion_reason": "",
    },
    # P18 - Brazdil 1994
    {
        "paper_id": "P18",
        "title": "Characterizing the Applicability of Classification Algorithms Using Meta-Level Learning",
        "authors": "Pavel Brazdil, Joao Gama, Bob Henery",
        "year": "1994",
        "venue": "ECML",
        "peer_reviewed": "yes",
        "paper_url": "https://link.springer.com/chapter/10.1007/3-540-57868-4_51",
        "code_url": "not reported",
        "doi": "10.1007/3-540-57868-4_51",
        "research_area": "Meta-learning",
        "selection_level": "Task",
        "task_domain": "Tabular",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "classical classifiers",
        "task_or_instance_features": "statistical meta-features",
        "predicted_outcomes": "algorithm applicability",
        "selection_objective": "algorithm selection",
        "evaluation_scheme": "cross-validation",
        "baselines": "not verified",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "Statistical meta-features can characterize algorithm applicability for classification tasks",
        "main_limitation": "Early foundational work; tabular data only; limited scale",
        "overlap_with_proposed_study": "Foundational task-level meta-learning for algorithm recommendation",
        "difference_from_proposed_study": "No text domain; no modern architectures; no operational outcomes",
        "novelty_threat_level": "low",
        "verification_status": "metadata_verified",
        "notes": "Foundational meta-learning paper",
        "verification_source": "Springer DOI resolution",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "",
        "exclusion_reason": "",
    },
    # P19 - Smith-Miles 2009
    {
        "paper_id": "P19",
        "title": "Cross-disciplinary perspectives on meta-learning for algorithm selection",
        "authors": "Kate Smith-Miles",
        "year": "2009",
        "venue": "ACM Computing Surveys",
        "peer_reviewed": "yes",
        "paper_url": "https://dl.acm.org/doi/10.1145/1459352.1459356",
        "code_url": "not reported",
        "doi": "10.1145/1459352.1459356",
        "research_area": "Algorithm selection",
        "selection_level": "Task",
        "task_domain": "General",
        "number_of_tasks_or_datasets": "not reported (survey)",
        "number_of_models_or_algorithms": "not reported (survey)",
        "candidate_system_types": "various algorithms",
        "task_or_instance_features": "problem features",
        "predicted_outcomes": "algorithm performance",
        "selection_objective": "algorithm recommendation",
        "evaluation_scheme": "survey",
        "baselines": "none (survey)",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "yes (discussed)",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "Synthesizes meta-learning approaches for algorithm selection across multiple disciplines",
        "main_limitation": "Survey paper; no new experiments",
        "overlap_with_proposed_study": "Comprehensive framework for task-level algorithm selection",
        "difference_from_proposed_study": "Survey; no text-specific focus; no LLMs",
        "novelty_threat_level": "low",
        "verification_status": "metadata_verified",
        "notes": "",
        "verification_source": "ACM DL page",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "",
        "exclusion_reason": "",
    },
    # P20 - Pfahringer 2000 Landmarking
    {
        "paper_id": "P20",
        "title": "Meta-Learning by Landmarking Various Learning Algorithms",
        "authors": "Bernhard Pfahringer, Hilan Bensusan, Christophe Giraud-Carrier",
        "year": "2000",
        "venue": "ICML",
        "peer_reviewed": "yes",
        "paper_url": "not reported",
        "code_url": "not reported",
        "doi": "not reported",
        "research_area": "Meta-learning",
        "selection_level": "Task",
        "task_domain": "Tabular",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "classical classifiers",
        "task_or_instance_features": "landmarking features (probe-model performance)",
        "predicted_outcomes": "algorithm accuracy",
        "selection_objective": "algorithm selection",
        "evaluation_scheme": "cross-validation",
        "baselines": "information-theoretic features",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "Landmarking features (running cheap probe algorithms) often outperform statistical meta-features",
        "main_limitation": "Tabular data only; classical classifiers",
        "overlap_with_proposed_study": "Task-level probe features for model recommendation",
        "difference_from_proposed_study": "No text domain; no LLMs; no operational outcomes",
        "novelty_threat_level": "low",
        "verification_status": "partially_verified",
        "notes": "URL not found for direct verification; referenced in Smith-Miles 2009 and Vanschoren 2018",
        "verification_source": "Secondary citation in Smith-Miles 2009",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "",
        "exclusion_reason": "",
    },
    # P21 - Vanschoren 2018
    {
        "paper_id": "P21",
        "title": "Meta-Learning: A Survey",
        "authors": "Joaquin Vanschoren",
        "year": "2018",
        "venue": "arXiv (also published in Automated Machine Learning, Springer 2019)",
        "peer_reviewed": "yes (book chapter)",
        "paper_url": "https://arxiv.org/abs/1810.03548",
        "code_url": "not reported",
        "doi": "10.48550/arXiv.1810.03548",
        "research_area": "Meta-learning",
        "selection_level": "Task",
        "task_domain": "General",
        "number_of_tasks_or_datasets": "not reported (survey)",
        "number_of_models_or_algorithms": "not reported (survey)",
        "candidate_system_types": "various",
        "task_or_instance_features": "meta-features",
        "predicted_outcomes": "performance",
        "selection_objective": "algorithm/model recommendation",
        "evaluation_scheme": "survey",
        "baselines": "none (survey)",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "Comprehensive survey of meta-learning approaches for algorithm recommendation and transfer",
        "main_limitation": "Survey; pre-LLM era",
        "overlap_with_proposed_study": "General meta-learning context",
        "difference_from_proposed_study": "Survey paper; no LLM routing; no validity",
        "novelty_threat_level": "low",
        "verification_status": "metadata_verified",
        "notes": "",
        "verification_source": "arXiv page: https://arxiv.org/abs/1810.03548",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "",
        "exclusion_reason": "",
    },
    # P22 - Kotthoff 2014
    {
        "paper_id": "P22",
        "title": "Algorithm Selection for Combinatorial Search Problems: A Survey",
        "authors": "Lars Kotthoff",
        "year": "2014",
        "venue": "AI Magazine",
        "peer_reviewed": "yes",
        "paper_url": "https://doi.org/10.1609/aimag.v35i3.2460",
        "code_url": "not reported",
        "doi": "10.1609/aimag.v35i3.2460",
        "research_area": "Algorithm selection",
        "selection_level": "Instance/Task",
        "task_domain": "Combinatorial search (SAT, CSP)",
        "number_of_tasks_or_datasets": "not reported (survey)",
        "number_of_models_or_algorithms": "not reported (survey)",
        "candidate_system_types": "solvers",
        "task_or_instance_features": "problem features",
        "predicted_outcomes": "runtime, solution quality",
        "selection_objective": "minimize runtime or maximize solution quality",
        "evaluation_scheme": "survey",
        "baselines": "none (survey)",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "yes (runtime prediction reviewed)",
        "handles_output_validity": "no",
        "main_finding": "Reviews algorithm selection for combinatorial problems; runtime prediction is central",
        "main_limitation": "Survey; non-ML focus; SAT/CSP domain",
        "overlap_with_proposed_study": "Task-level runtime/latency prediction from features",
        "difference_from_proposed_study": "Not ML classifiers or LLMs",
        "novelty_threat_level": "low",
        "verification_status": "metadata_verified",
        "notes": "",
        "verification_source": "DOI resolution",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "",
        "exclusion_reason": "",
    },
    # P23 - Hutter 2014
    {
        "paper_id": "P23",
        "title": "Algorithm Runtime Prediction: Methods and Evaluation",
        "authors": "Frank Hutter, Lin Xu, Holger H. Hoos, Kevin Leyton-Brown",
        "year": "2014",
        "venue": "Artificial Intelligence",
        "peer_reviewed": "yes",
        "paper_url": "https://doi.org/10.1016/j.artint.2013.10.003",
        "code_url": "not reported",
        "doi": "10.1016/j.artint.2013.10.003",
        "research_area": "Algorithm selection",
        "selection_level": "Instance",
        "task_domain": "SAT/Combinatorial",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "SAT solvers",
        "task_or_instance_features": "instance features",
        "predicted_outcomes": "runtime",
        "selection_objective": "runtime prediction",
        "evaluation_scheme": "cross-validation",
        "baselines": "random forest, ridge regression",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "yes (runtime prediction)",
        "handles_output_validity": "no",
        "main_finding": "Random forests are highly effective for empirical performance (runtime) models",
        "main_limitation": "SAT domain; not applied to modern ML or text tasks",
        "overlap_with_proposed_study": "Latency/runtime prediction from problem features",
        "difference_from_proposed_study": "SAT solvers, not heterogeneous ML/LLMs",
        "novelty_threat_level": "low",
        "verification_status": "metadata_verified",
        "notes": "",
        "verification_source": "DOI resolution",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "",
        "exclusion_reason": "",
    },
    # P24 - OOD-Chameleon (CORRECTED - remove fabricated arXiv ID)
    {
        "paper_id": "P24",
        "title": "OOD-Chameleon: Is Algorithm Selection Worth It for OOD Generalization?",
        "authors": "not verified",
        "year": "2024",
        "venue": "ICML 2024",
        "peer_reviewed": "yes",
        "paper_url": "https://icml.cc/virtual/2024/poster/33768",
        "code_url": "not reported",
        "doi": "not reported",
        "research_area": "Algorithm selection",
        "selection_level": "Task",
        "task_domain": "Vision (primarily)",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "OOD generalization algorithms",
        "task_or_instance_features": "dataset descriptors",
        "predicted_outcomes": "OOD generalization performance",
        "selection_objective": "algorithm ranking for OOD",
        "evaluation_scheme": "held-out datasets",
        "baselines": "ERM",
        "uses_oracle": "not verified",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "Dataset descriptors can learn non-trivial selection rules for OOD algorithms",
        "main_limitation": "Primarily vision domain; no text; no operational constraints",
        "overlap_with_proposed_study": "Task-level algorithm selection using dataset features",
        "difference_from_proposed_study": "Vision focus; no text; no validity or latency; homogeneous algorithm types",
        "novelty_threat_level": "moderate",
        "verification_status": "partially_verified",
        "notes": "Previously had fabricated arXiv ID 2402.00000; corrected to ICML poster URL",
        "verification_source": "Search results referencing ICML 2024 proceedings",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "Removed fabricated arXiv:2402.00000. Authors not fully verified.",
        "exclusion_reason": "",
    },
    # P25 - Koa-action (constrained classification)
    {
        "paper_id": "P25",
        "title": "Koa: Low-Latency Classification via Constrained Single-Token Decoding",
        "authors": "not verified",
        "year": "2024",
        "venue": "arXiv",
        "peer_reviewed": "no",
        "paper_url": "https://arxiv.org/abs/2609.15549",
        "code_url": "not reported",
        "doi": "not reported",
        "research_area": "Constrained decoding for classification",
        "selection_level": "Instance",
        "task_domain": "Text classification",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "1",
        "candidate_system_types": "LLMs",
        "task_or_instance_features": "text",
        "predicted_outcomes": "classification labels, latency",
        "selection_objective": "deterministic low-latency classification output",
        "evaluation_scheme": "empirical comparison",
        "baselines": "unconstrained LLM generation",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "yes (single-token reduces latency)",
        "handles_output_validity": "yes (deterministic label output)",
        "main_finding": "Single-token constrained decoding achieves low-latency, structurally valid classification",
        "main_limitation": "Method paper; not a selection problem",
        "overlap_with_proposed_study": "Demonstrates validity/latency trade-off in constrained LLM classification",
        "difference_from_proposed_study": "Method-level; not task-level selection across families",
        "novelty_threat_level": "low",
        "verification_status": "partially_verified",
        "notes": "Authors not fully verified from search results",
        "verification_source": "Search results and arXiv ID confirmed",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "",
        "exclusion_reason": "",
    },
    # P26 - ML-Plan
    {
        "paper_id": "P26",
        "title": "ML-Plan: Automated machine learning via hierarchical planning",
        "authors": "Felix Mohr, Marcel Wever, Eyke Huellermeier",
        "year": "2018",
        "venue": "Machine Learning",
        "peer_reviewed": "yes",
        "paper_url": "https://link.springer.com/article/10.1007/s10994-018-5735-z",
        "code_url": "not reported",
        "doi": "10.1007/s10994-018-5735-z",
        "research_area": "AutoML",
        "selection_level": "Task",
        "task_domain": "Tabular",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "ML pipelines",
        "task_or_instance_features": "none (search-based)",
        "predicted_outcomes": "accuracy",
        "selection_objective": "pipeline synthesis",
        "evaluation_scheme": "cross-validation",
        "baselines": "Auto-WEKA, auto-sklearn",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "Hierarchical planning effectively explores ML pipeline space",
        "main_limitation": "No task-level meta-features for zero-shot prediction",
        "overlap_with_proposed_study": "Pipeline/model selection at task level",
        "difference_from_proposed_study": "Search-based, not feature-based; no text; no LLMs; no validity",
        "novelty_threat_level": "low",
        "verification_status": "metadata_verified",
        "notes": "",
        "verification_source": "Springer DOI resolution",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "",
        "exclusion_reason": "",
    },
    # P27 - Routing Should Pay for Itself (CORRECTED - keep but note unverified authors)
    {
        "paper_id": "P27",
        "title": "Routing Should Pay for Itself",
        "authors": "not verified",
        "year": "2024",
        "venue": "arXiv",
        "peer_reviewed": "no",
        "paper_url": "https://arxiv.org/abs/2609.37402",
        "code_url": "not reported",
        "doi": "not reported",
        "research_area": "LLM routing",
        "selection_level": "Query",
        "task_domain": "Text",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "LLMs",
        "task_or_instance_features": "queries",
        "predicted_outcomes": "quality, routing overhead",
        "selection_objective": "minimize supervision cost of routing",
        "evaluation_scheme": "not verified",
        "baselines": "standard routing",
        "uses_oracle": "not verified",
        "uses_regret": "not verified",
        "handles_cost": "yes",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "Routing overhead can negate cost savings; proposes SaveRouter framework",
        "main_limitation": "Query-level; LLM-only",
        "overlap_with_proposed_study": "Cost optimization analysis for routing",
        "difference_from_proposed_study": "Query-level; LLM-only; no task-level features",
        "novelty_threat_level": "low",
        "verification_status": "partially_verified",
        "notes": "Authors not verified; arXiv ID confirmed from search",
        "verification_source": "Web search results",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "Downgraded from verified to partially_verified due to unverified authors",
        "exclusion_reason": "",
    },
    # P28 - You Cannot Pick a Provider (CORRECTED)
    {
        "paper_id": "P28",
        "title": "You Cannot Pick a Provider From the Price List",
        "authors": "not verified",
        "year": "2024",
        "venue": "arXiv",
        "peer_reviewed": "no",
        "paper_url": "https://arxiv.org/abs/2609.16278",
        "code_url": "not reported",
        "doi": "not reported",
        "research_area": "LLM routing / market analysis",
        "selection_level": "Query",
        "task_domain": "Text",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "LLM APIs",
        "task_or_instance_features": "provider pricing metadata",
        "predicted_outcomes": "quality, latency, cost",
        "selection_objective": "market analysis of provider selection",
        "evaluation_scheme": "empirical",
        "baselines": "none",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "yes",
        "handles_latency": "yes",
        "handles_output_validity": "no",
        "main_finding": "Price is weakly correlated with quality but strongly associated with latency",
        "main_limitation": "Market study; not a selection algorithm",
        "overlap_with_proposed_study": "Heterogeneous API comparison",
        "difference_from_proposed_study": "Not a predictive selection framework; LLMs only",
        "novelty_threat_level": "low",
        "verification_status": "partially_verified",
        "notes": "Authors not verified",
        "verification_source": "Web search results",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "Downgraded from verified to partially_verified",
        "exclusion_reason": "",
    },
    # P29 - CSCR
    {
        "paper_id": "P29",
        "title": "Cost-Spectrum Contrastive Routing",
        "authors": "not verified",
        "year": "2025",
        "venue": "arXiv",
        "peer_reviewed": "no",
        "paper_url": "https://arxiv.org/abs/2510.15545",
        "code_url": "not reported",
        "doi": "not reported",
        "research_area": "LLM routing",
        "selection_level": "Query",
        "task_domain": "Text",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "LLMs",
        "task_or_instance_features": "prompt embeddings in shared space",
        "predicted_outcomes": "cost, performance",
        "selection_objective": "microsecond-latency routing decisions",
        "evaluation_scheme": "benchmark comparison",
        "baselines": "predictive routers",
        "uses_oracle": "not verified",
        "uses_regret": "not verified",
        "handles_cost": "yes",
        "handles_latency": "yes (routing decision latency)",
        "handles_output_validity": "no",
        "main_finding": "Shared embedding space enables extremely fast (microsecond) routing decisions",
        "main_limitation": "Query-level; LLM-only",
        "overlap_with_proposed_study": "Efficiency of routing decisions",
        "difference_from_proposed_study": "Query-level; LLM-only; no task-level; no validity",
        "novelty_threat_level": "low",
        "verification_status": "partially_verified",
        "notes": "Authors not verified",
        "verification_source": "Web search results",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "Downgraded from verified to partially_verified",
        "exclusion_reason": "",
    },
    # P30 - Abdulrahman 2018 active testing
    {
        "paper_id": "P30",
        "title": "Speeding up algorithm selection using average ranking and active testing by introducing runtime",
        "authors": "Salisu Mamman Abdulrahman, Pavel Brazdil, Jan N. van Rijn, Joaquin Vanschoren",
        "year": "2018",
        "venue": "Machine Learning",
        "peer_reviewed": "yes",
        "paper_url": "https://link.springer.com/article/10.1007/s10994-017-5686-2",
        "code_url": "not reported",
        "doi": "10.1007/s10994-017-5686-2",
        "research_area": "Algorithm selection",
        "selection_level": "Task",
        "task_domain": "Tabular",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "classical classifiers",
        "task_or_instance_features": "landmarking, meta-features, runtime",
        "predicted_outcomes": "accuracy, runtime",
        "selection_objective": "minimize selection time",
        "evaluation_scheme": "cross-validation",
        "baselines": "random testing, average ranking",
        "uses_oracle": "not verified",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "yes (runtime incorporated)",
        "handles_output_validity": "no",
        "main_finding": "Active testing with runtime information speeds up algorithm selection",
        "main_limitation": "Tabular data; classical models only",
        "overlap_with_proposed_study": "Task-level selection with runtime/latency constraints",
        "difference_from_proposed_study": "No text domain; no LLMs; no output validity",
        "novelty_threat_level": "low",
        "verification_status": "metadata_verified",
        "notes": "",
        "verification_source": "Springer DOI resolution",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "",
        "exclusion_reason": "",
    },
    # P31-P35: Remaining papers from original matrix, cleaned
    {
        "paper_id": "P31",
        "title": "Collaborative Hyperparameter Tuning",
        "authors": "Remi Bardenet, Matyas Brendel, Balazs Kegl, Michele Sebag",
        "year": "2013",
        "venue": "ICML",
        "peer_reviewed": "yes",
        "paper_url": "https://proceedings.mlr.press/v28/bardenet13.html",
        "code_url": "not reported",
        "doi": "not reported",
        "research_area": "AutoML / Meta-learning",
        "selection_level": "Task",
        "task_domain": "Tabular",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "classifiers",
        "task_or_instance_features": "meta-features (surrogate transfer)",
        "predicted_outcomes": "accuracy",
        "selection_objective": "cross-task surrogate sharing for tuning",
        "evaluation_scheme": "empirical",
        "baselines": "independent tuning",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "Sharing information across dataset tuning tasks improves Bayesian optimization",
        "main_limitation": "No heterogeneous portfolio; tabular only",
        "overlap_with_proposed_study": "Cross-task transfer via meta-features",
        "difference_from_proposed_study": "Focuses on HPO, not discrete heterogeneous selection; no text",
        "novelty_threat_level": "low",
        "verification_status": "metadata_verified",
        "notes": "",
        "verification_source": "PMLR page",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "",
        "exclusion_reason": "",
    },
    {
        "paper_id": "P32",
        "title": "AlphaD3M: Machine Learning Pipeline Synthesis and AutoML",
        "authors": "Iddo Drori, Yamuna Krishnamurthy, Remi Louber, Raoni de Paula Louback, et al.",
        "year": "2021",
        "venue": "Journal of Machine Learning Research",
        "peer_reviewed": "yes",
        "paper_url": "https://jmlr.org/papers/v22/18-543.html",
        "code_url": "not reported",
        "doi": "not reported",
        "research_area": "AutoML",
        "selection_level": "Task",
        "task_domain": "Tabular/Text",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "ML pipelines",
        "task_or_instance_features": "meta-features",
        "predicted_outcomes": "accuracy",
        "selection_objective": "pipeline generation via reinforcement learning",
        "evaluation_scheme": "empirical",
        "baselines": "TPOT, Auto-WEKA",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "RL-based pipeline synthesis competitive with existing AutoML approaches",
        "main_limitation": "Focus on pipeline construction; no validity constraints",
        "overlap_with_proposed_study": "Task-level pipeline/model selection",
        "difference_from_proposed_study": "No output validity; no LLMs; construction not selection",
        "novelty_threat_level": "low",
        "verification_status": "metadata_verified",
        "notes": "Corrected venue from AutoML Workshop to JMLR 2021",
        "verification_source": "JMLR page",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "Corrected year from 2018 to 2021; venue from workshop to JMLR",
        "exclusion_reason": "",
    },
    {
        "paper_id": "P33",
        "title": "Meta-learning for evolutionary parameter optimization of classifiers",
        "authors": "Matthias Reif, Faisal Shafait, Andreas Dengel",
        "year": "2012",
        "venue": "Machine Learning",
        "peer_reviewed": "yes",
        "paper_url": "https://link.springer.com/article/10.1007/s10994-012-5286-7",
        "code_url": "not reported",
        "doi": "10.1007/s10994-012-5286-7",
        "research_area": "AutoML / Meta-learning",
        "selection_level": "Task",
        "task_domain": "Tabular",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "classical classifiers",
        "task_or_instance_features": "meta-features",
        "predicted_outcomes": "accuracy",
        "selection_objective": "evolutionary hyperparameter search",
        "evaluation_scheme": "cross-validation",
        "baselines": "grid search",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "Meta-learning speeds up evolutionary hyperparameter search across datasets",
        "main_limitation": "Classical classifiers only; tabular",
        "overlap_with_proposed_study": "Task-level meta-learning",
        "difference_from_proposed_study": "HPO focus; no text; no LLMs; no validity or regret",
        "novelty_threat_level": "low",
        "verification_status": "metadata_verified",
        "notes": "",
        "verification_source": "Springer DOI resolution",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "",
        "exclusion_reason": "",
    },
    {
        "paper_id": "P34",
        "title": "Measures of Complexity in Classification Problems",
        "authors": "Tin Kam Ho, Mitra Basu",
        "year": "2002",
        "venue": "IEEE TPAMI",
        "peer_reviewed": "yes",
        "paper_url": "https://doi.org/10.1109/34.990132",
        "code_url": "not reported",
        "doi": "10.1109/34.990132",
        "research_area": "Dataset meta-features",
        "selection_level": "Task",
        "task_domain": "Tabular",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "classifiers (analyzed)",
        "task_or_instance_features": "complexity measures (overlap, separability, topology)",
        "predicted_outcomes": "dataset complexity characterization",
        "selection_objective": "understanding classifier behavior",
        "evaluation_scheme": "empirical",
        "baselines": "not reported",
        "uses_oracle": "no",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "Complexity measures capture dataset difficulty beyond simple statistics",
        "main_limitation": "Tabular; not used for automated selection",
        "overlap_with_proposed_study": "Dataset characterization features",
        "difference_from_proposed_study": "Foundational complexity measures; not selection or text",
        "novelty_threat_level": "low",
        "verification_status": "metadata_verified",
        "notes": "Foundational data complexity paper",
        "verification_source": "IEEE DOI resolution",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "New entry replacing Sun et al. 2013 which had insufficient verification",
        "exclusion_reason": "",
    },
    {
        "paper_id": "P35",
        "title": "METAOD: Automated Unsupervised Outlier Detection via Meta-Learning",
        "authors": "Yue Zhao, Ryan A. Rossi, Leman Akoglu",
        "year": "2021",
        "venue": "NeurIPS",
        "peer_reviewed": "yes",
        "paper_url": "https://proceedings.neurips.cc/paper/2021/hash/23c89427e4e0545b5e47e75ac8e4c3ff-Abstract.html",
        "code_url": "https://github.com/yzhao062/MetaOD",
        "doi": "not reported",
        "research_area": "Meta-learning / Algorithm selection",
        "selection_level": "Task",
        "task_domain": "Tabular (outlier detection)",
        "number_of_tasks_or_datasets": "not verified",
        "number_of_models_or_algorithms": "not verified",
        "candidate_system_types": "outlier detection algorithms",
        "task_or_instance_features": "meta-features",
        "predicted_outcomes": "algorithm performance",
        "selection_objective": "unsupervised model selection",
        "evaluation_scheme": "held-out datasets",
        "baselines": "random selection, global best",
        "uses_oracle": "not verified",
        "uses_regret": "no",
        "handles_cost": "no",
        "handles_latency": "no",
        "handles_output_validity": "no",
        "main_finding": "Meta-learning from dataset features enables effective unsupervised model selection",
        "main_limitation": "Outlier detection domain; no text; no validity",
        "overlap_with_proposed_study": "Task-level meta-learning for model selection without labels",
        "difference_from_proposed_study": "Different domain; no text; no LLMs; no validity",
        "novelty_threat_level": "low",
        "verification_status": "metadata_verified",
        "notes": "",
        "verification_source": "NeurIPS proceedings page",
        "verification_date": "2026-10-03",
        "full_text_checked": "no",
        "correction_notes": "New addition replacing earlier unverified entry",
        "exclusion_reason": "",
    },
]

csv_file = docs_dir / "literature_matrix.csv"
with csv_file.open("w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    for p in papers:
        writer.writerow(p)

print(f"Wrote {len(papers)} papers to {csv_file}")
